version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: ['9090:9090']
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/prometheus/rules.d:/etc/prometheus/rules.d
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports: ['9093:9093']
    volumes:
      - /srv/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ['3000:3000']
    volumes:
      - /srv/grafana/provisioning:/etc/grafana/provisioning
      - /srv/grafana/dashboards:/var/lib/grafana/dashboards
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports: ['9100:9100']
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports: ['9115:9115']
    volumes:
      - /srv/blackbox_exporter/blackbox.yml:/etc/blackbox_exporter/config.yml
